[package]
name = "wasm-unknown-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = "0.3"
rustpython-vm = { path = "../../crates/vm", default-features = false, features = ["compiler"] }
static_assertions = "1.1"

[workspace]

[patch.crates-io]
